version: 2
jobs:
  install:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - run: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  tests:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run: npm run lint
        - run: npm run test
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run release
workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - tests:
          requires:
            - install
      - release:
          requires:
            - tests
          filters:
            branches:
              only: master
